### ISSUE TITLE
Web compile issue

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#277] opened 2018-07-06 16:07 UTC
Here is the error message:

~~~shell
To start a web server for remote viewing:
  cd web/output
  origen web serve
[INFO]       85.256[0.008]   || **********************************************************************
[INFO]       85.278[0.022]   || Compiling... templates/web/index.md.erb
[INFO]       85.279[0.001]   ||   Created... web/content/index.md

COMPLETE CALL STACK
-------------------
/users/user/origen/prod/ppekit/config/version.rb:3: Invalid octal digit
  MINOR = 09
            ^
/users/user/origen/ruby/2.3.0/bundler/gems/origen-8ae1851cb392/lib/origen/application.rb:384:in `load'
/users/user/origen/ruby/2.3.0/bundler/gems/origen-8ae1851cb392/lib/origen/application.rb:384:in `version'
(erb):5:in `block in _get_binding'
~~~

I understand that 9 is not an octal number but why would it be looking for Octal at all?  Any ideas?

**Comment by pderouen** [comment] 2018-07-06 16:20
Apparently, the leading zero indicates the number is represented in octal:
origen(main):003:0> a=077
=> 63

**Comment by pderouen** [comment] 2018-07-06 16:47
https://ruby-doc.org/core-2.3.0/doc/syntax/literals_rdoc.html

Seems odd that 0 or 0o would be interpreted as octal by ruby.  Who uses octal?

**Comment by coreyeng** [comment] 2018-07-06 17:02
The only way I could see that happening is if the <code>config/version.rb</code> was manually changed to put <code>09</code> in the minor field. The <code>tag</code> operation should have put <code>9</code> for just an increment, unless a custom tag of the form <code>1.2.09</code> was used. I'm not sure if <code>origen rc tag</code> would actually check it.

Can you check the <code>config/version.rb</code> and see what the <code>minor</code> field looks like? You might need to manually fix it to just <code>9</code>, but I'm not sure how it would have gotten that way in the first place.

**Comment by ginty** [comment] 2018-07-24 14:00
Agree that this looks most likely to be caused by a hand-edit gone wrong, and there is no clear way to fix it since it is failing at the Ruby file loading stage before Origen can even get a look at it.

Therefore closing this as not an issue, but feel free to re-open if you think otherwise.

**Closed by ginty** 2018-07-24 14:00 UTC
