### ISSUE TITLE
NVM error with Origen +0.40.2

### ISSUE THREAD

**Issue by RobKang3** [Origen-SDK/origen#322] opened 2019-01-10 03:50 UTC
The update in reg.rb file on 14th/Dec from 0.41.0 caused c90tfs_nvm_tester failed to generate patterns.
The adding in line 95 as below caused Marshal.load dump format error for symbol.
options.each_value { |bit_desc| bit_desc[:pos] = @size - bit_desc[:pos] - bit_desc[:bits] } if bit_order == :msb0
Below is the head of error info:
Generating...  /proj/k4l1_users1/b50956/pge/kw41/output/nvm/nvm_bistcom_debug.atp                                                                                  

COMPLETE CALL STACK
-------------------
dump format error for symbol(0x6f)
/home/nxa13790/.origen/gems/ruby/2.3.0/gems/c90tfs_nvm_tester-1.10.0.pre4/lib/c90tfs_nvm_tester/parameters.rb:142:in `load'

If more data needed pls let me know, thanks.

**Comment by pderouen** [comment] 2019-01-16 21:34
Closing this issue. The root cause was outside of Origen.

**Closed by pderouen** 2019-01-16 21:34 UTC

**Comment by info-rchitect** [comment] 2019-01-16 21:35
@pderouen was it due to the operating system changing, preventing the Marshal from working correctly?

**Comment by pderouen** [comment] 2019-01-16 22:07
@ginty debugged the issue. He'll have to fill in details for you. I think it was something with the class having a bit_order attribute.

**Comment by ginty** [comment] 2019-01-17 09:32
I think it was caused by a bug in Ruby, but I couldn't narrow it down to a simple test case (e.g. so that I could report it).
In summary, this update to Origen caused models that own registers to have a new instance variable - `@bit_order` with the value `:lsb0`, and somehow this led to the reported error.
It was very clear, by modifying the code to prevent this instance variable being set would turn it on and off.
What Origen was doing was perfectly legal and it definitely didn't stop all objects mashalling, in fact I was not able to replicate it at all in a test case, but it did with this particular object.
The workaround I applied was simply to wrap the object in an array before marshalling it, and that fixed.
If an object can marshal inside an array it should be able to marshal outside of one, and if it can't, that's a Ruby bug.
