### ISSUE TITLE
Origen not driving pins at time 0 in simulation

### ISSUE THREAD

**Issue by jiangliu23** [Origen-SDK/origen#415] opened 2020-12-08 16:27 UTC
When adding a new pin and initializing the state of the pin using code like below, it appears that the pins are not being driven to the expected state in simulation at T0, the versions of Origen that have broken this seems to be 0.59.4 and 0.59.5

~~~ruby
add_pin :io_1, direction: :input, reset: :drive_lo
~~~

So Origen 0.59.3 (passes with no issue)
Origen 0.59.4 (broken)
Origen 0.59.5 (broken)

**Comment by ginty** [comment] 2020-12-08 16:40
Pretty sure this is related to https://github.com/Origen-SDK/origen/pull/407

@info-rchitect, @priyavadan, I think we need to consider rolling back on that.

I'm not sure exactly where the problem lies, but I would guess somewhere it is assuming that a nil pin type means digital (vs. analog day) and now that code is broken because such pins now have a pin type called signal.
Something along those lines I think.

**Comment by info-rchitect** [comment] 2020-12-08 16:51
@ginty I would just roll it back until we can figure out where the gap in the spec tests exist that would cover this unknown connection.  Let me see when I can get to it.

**Comment by ginty** [comment] 2020-12-08 17:21
I think the problem in this case is caused by this method - https://github.com/Origen-SDK/origen_sim/blob/master/lib/origen_sim/origen/top_level.rb#L8

Previously if you called it with `rtl_pins(type: :digital)` then it would also return pins with no type, but since such pins now have a type of `:signal` they now don't get returned.

We could patch that method easily enough, however I think pins going from having no type by default to having a type is a change in behavior which we should not do - its possible other apps may run into issues when they upgrade in the future and would rightly call this a potentially breaking change.

So what do you want to do, roll back on that update completely? Or keep most of it around and just remove the defaulting to `:signal`?
The latter would allow you to either assign `:signal` as the type within your app, or else implement a default of `nil == :signal` within your app.

**Comment by info-rchitect** [comment] 2020-12-08 17:23
@ginty https://github.com/Origen-SDK/origen/pull/416

I would just revert and force people to set it when adding pins.  I do think we should add a spec test to protect the current behavior.  I will make a new PR that allows people to set the pin type to something other than `:digital` or ':analog`.  Let me know if you agree.

**Comment by ginty** [comment] 2020-12-08 17:26
Ok thanks @info-rchitect, sounds good!

**Comment by jiangliu23** [comment] 2020-12-08 17:33
> @ginty #416
> 
> I would just revert and force people to set it when adding pins. I do think we should add a spec test to protect the current behavior. I will make a new PR that allows people to set the pin type to something other than `:digital` or ':analog`. Let me know if you agree.

BTW, does this mean anyone who wishes to upgrade to newer versions origen is subjected to updating all of their pin instantiation code to explicitly define the pin type?

**Comment by ginty** [comment] 2020-12-08 17:55
No, it means that no definition means no specific type as it does today

**Comment by jiangliu23** [comment] 2020-12-08 18:39
> No, it means that no definition means no specific type as it does today

thanks for clarifying!

**Comment by info-rchitect** [comment] 2020-12-08 19:05
@jiangliu23 Fixed in 0.59.6

**Closed** 2020-12-08 19:05 UTC

**Comment by jiangliu23** [comment] 2020-12-08 19:17
> @jiangliu23 Fixed in 0.59.6

great thanks!
